"""The write path, exercised against a real PostGIS.

A unit test can prove `persist_window` was called. Only these can prove the
SQL that runs is the SQL we meant: that PostGIS derives `geom`, that a replay
is a no-op, that a type-24 frame cannot erase a ship type, and that the
window and its run row share a transaction.

Run them with the test database up (README §4). They do not skip.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from dataclasses import fields
from datetime import UTC, datetime, timedelta
from pathlib import Path

import pytest
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import func, select, text

from alembic import command
from app.db.session import session_scope
from app.ingestion.buffer import WindowBatch
from app.ingestion.persistence import persist_window
from app.ingestion.pipeline import process_window
from app.models import IngestionRun, Vessel, VesselPosition
from app.providers.base import PositionSample, StaticSample
from app.worker import IngestionWorker

pytestmark = pytest.mark.integration

BACKEND = Path(__file__).resolve().parents[2]

#: A point inside the default bounding box (Santo Domingo).
LATITUDE = 18.4717
LONGITUDE = -69.9300

BASE = datetime(2026, 10, 6, 12, 0, tzinfo=UTC)


def position(mmsi: int = 373_123_456, *, minute: int = 0, **overrides: object) -> PositionSample:
    """A position validation accepts: nine-digit MMSI, coordinates in range."""
    return PositionSample(
        mmsi=mmsi,
        timestamp=BASE + timedelta(minutes=minute),
        latitude=LATITUDE,
        longitude=LONGITUDE,
        received_at=BASE + timedelta(minutes=minute, seconds=4),
        source="aisstream.io",
        **overrides,
    )


def static(mmsi: int = 373_123_456, *, minute: int = 0, **overrides: object) -> StaticSample:
    return StaticSample(
        mmsi=mmsi,
        received_at=BASE + timedelta(minutes=minute),
        source="aisstream.io",
        **overrides,
    )


def window(
    *, positions: list[PositionSample] | None = None, statics: list[StaticSample] | None = None
) -> None:
    """Validate a batch and persist it the way a flush does."""
    positions = positions or []
    result = process_window(
        WindowBatch(
            positions=positions,
            statics=statics or [],
            vessels=len({sample.mmsi for sample in positions}),
            throttled=0,
            evicted=0,
        )
    )
    persist_window(
        result,
        window_start=BASE,
        window_end=BASE + timedelta(minutes=10),
        reason="scheduled",
    )


def count_of(model: type) -> int:
    with session_scope() as session:
        return session.execute(select(func.count()).select_from(model)).scalar_one()


# ── the round trip ──────────────────────────────────────────────────────


def test_every_sample_field_survives_the_round_trip() -> None:
    """A field added to the sample but not to the table would vanish silently."""
    sample = position(
        373_123_456,
        sog=11.2,
        cog=142.5,
        heading=141,
        rot=-7,
        nav_status=0,
        ship_name="SEA VOYAGER",
    )
    window(positions=[sample])

    with session_scope() as session:
        stored = session.execute(select(VesselPosition)).scalars().one()

    for field in fields(PositionSample):
        assert getattr(stored, field.name) == getattr(sample, field.name), field.name


def test_the_run_row_counts_exactly_what_was_written() -> None:
    window(
        positions=[position(373_123_456), position(373_123_456, minute=5)],
        statics=[static()],
    )

    with session_scope() as session:
        run = session.execute(select(IngestionRun)).scalars().one()

    assert run.positions == 2
    assert run.statics == 1
    assert run.vessels == 1
    assert run.window_start == BASE
    assert run.window_end == BASE + timedelta(minutes=10)
    assert run.reason == "scheduled"
    assert run.rejected == {}
    assert run.flagged == {}


# ── idempotency (§6) ────────────────────────────────────────────────────


def test_replaying_a_window_does_not_duplicate_positions() -> None:
    """A crash after the write but before the drain must not double a track."""
    window(positions=[position(), position(minute=5)])
    window(positions=[position(), position(minute=5)])

    assert count_of(VesselPosition) == 2
    # The run row is *not* deduplicated: two flushes are two events, and the
    # second one is the evidence that a retry happened.
    assert count_of(IngestionRun) == 2


def test_an_empty_window_still_writes_its_run_row() -> None:
    """The keepalive that stops an idle Supabase project from being paused."""
    result = process_window(
        WindowBatch(positions=[], statics=[], vessels=0, throttled=0, evicted=0)
    )
    persist_window(result, window_start=None, window_end=BASE, reason="scheduled")

    with session_scope() as session:
        run = session.execute(select(IngestionRun)).scalars().one()

    assert count_of(VesselPosition) == 0
    assert run.positions == 0
    assert run.window_start is None  # first window: nothing precedes it


# ── identity merge ──────────────────────────────────────────────────────


def test_a_message_that_omits_a_field_cannot_erase_it() -> None:
    """Type 24 part A carries a name and nothing else."""
    window(statics=[static(ship_type=70, destination="KINGSTOWN", name="SEA VOYAGER")])
    window(statics=[static(minute=10, name="SEA VOYAGER II")])

    with session_scope() as session:
        vessel = session.execute(select(Vessel)).scalars().one()

    assert vessel.name == "SEA VOYAGER II"  # what it carried, replaces
    assert vessel.ship_type == 70  # what it did not, survives
    assert vessel.destination == "KINGSTOWN"


def test_a_field_that_changed_with_the_voyage_does_replace() -> None:
    """Freezing `destination` at first sighting would make `vessels` a museum."""
    window(statics=[static(destination="KINGSTOWN")])
    window(statics=[static(minute=10, destination="PORT OF SPAIN")])

    with session_scope() as session:
        vessel = session.execute(select(Vessel)).scalars().one()

    assert vessel.destination == "PORT OF SPAIN"


# ── the transform, verified at the column ───────────────────────────────


def test_the_wire_hull_offsets_become_a_size() -> None:
    """`length = A + B`, `width = C + D` — and a half sum stores nothing."""
    window(statics=[static(dim_a=100, dim_b=50, dim_c=20, dim_d=10)])
    window(statics=[static(minute=10, mmsi=373_654_321, dim_a=100, dim_c=20, dim_d=10)])

    with session_scope() as session:
        complete, partial = session.execute(select(Vessel).order_by(Vessel.mmsi)).scalars().all()

    assert (complete.length_m, complete.width_m) == (150, 30)
    # The stern half never arrived, so there is no length — not half of one.
    assert partial.length_m is None
    assert partial.width_m == 30


def test_geom_is_derived_from_the_stored_coordinates() -> None:
    """The database builds the point; nobody else does, so nobody can get it wrong."""
    window(positions=[position()])

    with session_scope() as session:
        distance = session.execute(
            text(
                "SELECT ST_Distance(geom, ST_SetSRID("
                "ST_MakePoint(:longitude, :latitude), 4326)::geography) "
                "FROM vessel_positions"
            ),
            {"longitude": LONGITUDE, "latitude": LATITUDE},
        ).scalar_one()

    assert distance < 1.0  # within a metre of the exact stored coordinates


# ── the seam and the migration ──────────────────────────────────────────


class _IdleProvider:
    """Stands in for the stream; `flush_once` never calls `samples()`."""

    name = "idle"
    frames = 0
    decode_errors = 0
    unusable = 0
    reconnects = 0

    async def samples(self) -> AsyncIterator[PositionSample]:
        """Never consumed — the test fills the buffer itself."""
        return
        yield  # makes this an async generator without producing anything


async def test_a_flush_reaches_the_database_through_the_seam() -> None:
    """`flush_once` → `_report` → `persist_window`, wired for real."""
    worker = IngestionWorker(_IdleProvider())
    worker.buffer.add_position(position())
    worker.buffer.add_static(static())

    result = await worker.flush_once(reason="scheduled")

    assert len(result.positions) == 1
    assert (count_of(VesselPosition), count_of(Vessel), count_of(IngestionRun)) == (1, 1, 1)
    # The window drained: the next flush starts from nothing but the throttle.
    assert len(worker.buffer) == 0


def test_the_migration_has_not_drifted_from_the_models() -> None:
    """`alembic check`: what ships to Supabase is what the code expects."""
    config = Config(str(BACKEND / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND / "alembic"))

    try:
        command.check(config)
    except AutogenerateDiffsDetected as error:
        pytest.fail(f"migration and models disagree: {error}")
