"""create maritime schema

Revision ID: 58ed61b993fd
Revises: 
Create Date: 2026-10-06 21:04:17.642107
"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '58ed61b993fd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate cannot see extensions — it only compares tables. Without
    # this, `geography(POINT,4326)` below is an unknown type on a database
    # where nobody installed PostGIS yet (a fresh Supabase project has it
    # available but not enabled).
    #
    # The extension is deliberately NOT dropped in `downgrade()`: PostGIS is
    # shared infrastructure, and removing it would take every geography column
    # in the database with it.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('positions', sa.Integer(), nullable=False),
    sa.Column('statics', sa.Integer(), nullable=False),
    sa.Column('vessels', sa.Integer(), nullable=False),
    sa.Column('throttled', sa.Integer(), nullable=False),
    sa.Column('evicted', sa.Integer(), nullable=False),
    sa.Column('rejected', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flagged', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # The GiST index on `geom` is deliberately NOT an op below: geoalchemy2
    # creates it from its `after_create` listener the instant this table
    # exists, while autogenerate separately emits an op for it because the
    # index lives in the table's metadata. Emitting both makes `CREATE INDEX`
    # run twice and the migration fail with "relation already exists".
    op.create_table('vessel_positions',
    sa.Column('mmsi', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('sog', sa.Float(), nullable=True),
    sa.Column('cog', sa.Float(), nullable=True),
    sa.Column('heading', sa.SmallInteger(), nullable=True),
    sa.Column('rot', sa.SmallInteger(), nullable=True),
    sa.Column('nav_status', sa.SmallInteger(), nullable=True),
    sa.Column('ship_name', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), sa.Computed('ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography', persisted=True), nullable=False),
    sa.PrimaryKeyConstraint('mmsi', 'timestamp')
    )
    op.create_index('ix_vessel_positions_timestamp', 'vessel_positions', ['timestamp'], unique=False)
    op.create_table('vessels',
    sa.Column('mmsi', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('callsign', sa.Text(), nullable=True),
    sa.Column('imo', sa.Integer(), nullable=True),
    sa.Column('ship_type', sa.SmallInteger(), nullable=True),
    sa.Column('length_m', sa.SmallInteger(), nullable=True),
    sa.Column('width_m', sa.SmallInteger(), nullable=True),
    sa.Column('draught_m', sa.Float(), nullable=True),
    sa.Column('destination', sa.Text(), nullable=True),
    sa.Column('eta', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('mmsi')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vessels')
    op.drop_index('ix_vessel_positions_timestamp', table_name='vessel_positions')
    op.drop_index('idx_vessel_positions_geom', table_name='vessel_positions', postgresql_using='gist')
    op.drop_table('vessel_positions')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
